# This is a basic workflow that is manually triggered

name: Test PR

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Test
      run: |
        touch test.txt 

    - name: PR
      uses: peter-evans/create-pull-request@v6
      with: 
        branch: test/pr
        title: "Auto PR"
        body: |
          testing github action 
        add-paths:
          test.txt
        commit-message: Push test.txt 
        delete-branch: true
        reviewers: blackshushi
        token: ${{ secrets.GITHUB_TOKEN }}
